# V4L2 Test Configuration

print_to_console: false          # Enable/disable timestamp printing to console
use_posix_format: false         # Use POSIX epoch time instead of CLOCK_MONOTONIC
enable_file_logging: false      # Enable/disable logging to file
log_filename: ""                # Log filename (empty = no logging)
show_fps: true                  # Show FPS in output
